### ISSUE TITLE
Comments and cursor are not visible

### ISSUE THREAD

**Issue by blez** [pushqrdx/emacs-elementary-themes#1]
When using in Doom Emacs I can't see my cursor and commented code - they have same color as a background

**Comment by pushqrdx** [comment]
@blez Are you on Emacs 29?

**Comment by blez** [comment]
> @blez Are you on Emacs 29?

Yes

**Comment by pushqrdx** [comment]
@blez Yeah that was due to a change Emacs did to `color.el`, i have pushed a fix for it, should be working fine now, would be nice if you give it a test

**Comment by blez** [comment]
The bug was fixed, thank you. But there is another issue.
Completion highlight line has same color as background so it's invisible
https://i.imgur.com/1BYk4xv.png

**Comment by pushqrdx** [comment]
@blez what completion framework is this?

**Comment by blez** [comment]
company

**Comment by pushqrdx** [comment]
@blez alright, pushed another commit, in the picture it looks like company-box mode which uses childframes. Here's how it looks now, and obviously it will adapt 

![image](https://user-images.githubusercontent.com/25884937/172244908-76a058cd-f69d-49e8-9ee7-5458eb12f288.png)

**Comment by blez** [comment]
Thanks
